version: "3.8"
services:
  mongodb-esisba:
    image: mongo
    container_name: mongo-esi
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - "./data:/data/db:rw"
    ports:
      - 27017:27017
    restart: unless-stopped
